## Librerias

In [2]:
import requests
import warnings
import json
import requests
import pandas as pd
warnings.filterwarnings('ignore')

## Tabla de Races

In [3]:
races={'season': [],
      'round':[],
      'raceName':[],
      'circuitId':[],
      'lat':[],
      'long':[],
      'country':[],
      'date':[],
      'url':[]}

In [4]:
for year in list(range(2010,2023)):
    url='http://ergast.com/api/f1/{}.json'
    response=requests.get(url.format(year))
    content=json.loads(response.content)

In [6]:
for year in list(range(2010,2023)):
    url='http://ergast.com/api/f1/{}.json'
    response=requests.get(url.format(year))
    content=json.loads(response.content)
    for item in content ['MRData']['RaceTable']['Races']:
        
            races['season'].append(int(item['season']))
            races['round'].append(int(item['round']))
            races['raceName'].append(item['raceName'])
            races['circuitId'].append(item['Circuit']['circuitId'])
            races['lat'].append(item['Circuit']['Location']['lat'])
            races['long'].append(item['Circuit']['Location']['long'])
            races['country'].append(item['Circuit']['Location']['country'])
            races['date'].append(item['date'])
            races['url'].append(item['url'])

In [60]:
#races['season']
for key in races.keys():
    print(len(races[key]))

259
259
259
259
259
259
259
259
259

In [61]:
 pd.DataFrame(races)

,season,round,raceName,circuitId,lat,long,country,date,url
0,2010,1,Bahrain Grand Prix,bahrain,26.0325,50.5106,Bahrain,2010-03-14,http://en.wikipedia.org/wiki/2010_Bahrain_Gran...
1,2010,2,Australian Grand Prix,albert_park,-37.8497,144.968,Australia,2010-03-28,http://en.wikipedia.org/wiki/2010_Australian_G...
2,2010,3,Malaysian Grand Prix,sepang,2.76083,101.738,Malaysia,2010-04-04,http://en.wikipedia.org/wiki/2010_Malaysian_Gr...
3,2010,4,Chinese Grand Prix,shanghai,31.3389,121.22,China,2010-04-18,http://en.wikipedia.org/wiki/2010_Chinese_Gran...
4,2010,5,Spanish Grand Prix,catalunya,41.57,2.26111,Spain,2010-05-09,http://en.wikipedia.org/wiki/2010_Spanish_Gran...
...,...,...,...,...,...,...,...,...,...
254,2022,18,Japanese Grand Prix,suzuka,34.8431,136.541,Japan,2022-10-09,http://en.wikipedia.org/wiki/2022_Japanese_Gra...
255,2022,19,United States Grand Prix,americas,30.1328,-97.6411,USA,2022-10-23,http://en.wikipedia.org/wiki/2022_United_State...
256,2022,20,Mexico City Grand Prix,rodriguez,19.4042,-99.0907,Mexico,2022-10-30,http://en.wikipedia.org/wiki/2022_Mexican_Gran...
257,2022,21,Brazilian Grand Prix,interlagos,-23.7036,-46.6997,Brazil,2022-11-13,http://en.wikipedia.org/wiki/2022_Brazilian_Gr...
258,2022,22,Abu Dhabi Grand Prix,yas_marina,24.4672,54.6031,UAE,2022-11-20,http://en.wikipedia.org/wiki/2022_Abu_Dhabi_Gr...

In [49]:
url="http://ergast.com/api/f1/seasons.json"
response=requests.get(url.format(year))
content=json.loads(response.content)

In [51]:
se={"season":[],"url":[]}
for item in content["MRData"]["SeasonTable"]["Seasons"]:
    se["season"].append(int(item["season"]))
    se["url"].append(item["url"])

In [52]:
pd.DataFrame(races).to_csv('races.csv',index=False)
pd.DataFrame(se).to_csv('seasons.csv',index=False)

In [75]:

#pd.DataFrame(content['MRData']['RaceTable']['Races'][0]['Results'])

## Tabla de Resultados

In [8]:
df_results_2022=pd.DataFrame()
for race in list(range(1,23)):
    url='http://ergast.com/api/f1/2022/22/results.json'
    response=requests.get(url.format(race))
    content=json.loads(response.content)
    #list_results_2022.append(content['MRData']['RaceTable']['Races'][0]['Results'])
    df_results_2022=df_results_2022.append(pd.DataFrame(content['MRData']['RaceTable']['Races'][0]['Results']))

In [9]:
df_results_2022['Driver']=df_results_2022['Driver'].apply(lambda x: x['driverId'])

In [10]:
df_results_2022['points']=df_results_2022['points'].astype(int)

In [11]:
df_results_2022.groupby(['Driver']).agg({'points':'sum'}).sort_values(by='points',ascending=False)

                 points
Driver
max_verstappen      550
leclerc             396
perez               330
sainz               264
russell             220
norris              198
ocon                132
stroll               88
ricciardo            44
vettel               22
tsunoda               0
albon                 0
alonso                0
mick_schumacher       0
latifi                0
kevin_magnussen       0
hamilton              0
gasly                 0
bottas                0
zhou                  0

In [22]:
df_results_2022['Constructor']=df_results_2022['Constructor'].apply(lambda x: x['constructorId'])

#df_results_2022['points']=df_results_2022['points'].astype(int)
#df_results_2022.groupby(['Constructor']).agg({'points':'sum'}).sort_values(by='points',ascending=False)

TypeError: string indices must be integers